from fastapi import APIRouter

from app.api.v1 import (
    admin,
    analytics,
    api_tokens,
    attachments,
    auth,
    calendar,
    chat,
    comments,
    docs,
    forms,
    github,
    goals,
    integration_oauth,
    integration_oauth_apps,
    integrations,
    integrations_realtime,
    mcp_oauth,
    my_analytics,
    notifications,
    organizations,
    projects,
    search,
    sprints,
    tasks,
    teams,
    templates,
    time_entries,
    two_factor,
    users,
    webhooks,
    whiteboards,
    workspaces,
    ws,
)

api_router = APIRouter(prefix="/api/v1")
api_router.include_router(auth.router)
api_router.include_router(api_tokens.router)
api_router.include_router(mcp_oauth.router)
api_router.include_router(mcp_oauth.mcp_router)
api_router.include_router(integration_oauth.router)
api_router.include_router(integration_oauth_apps.router)
api_router.include_router(two_factor.router)
api_router.include_router(users.router)
api_router.include_router(organizations.router)
api_router.include_router(webhooks.router)
api_router.include_router(workspaces.router)
api_router.include_router(projects.router)
api_router.include_router(tasks.router)
api_router.include_router(comments.router)
api_router.include_router(notifications.router)
api_router.include_router(chat.router)
api_router.include_router(time_entries.router)
api_router.include_router(sprints.router)
api_router.include_router(goals.router)
api_router.include_router(github.router)
api_router.include_router(teams.router)
api_router.include_router(templates.router)
api_router.include_router(whiteboards.router)
api_router.include_router(docs.router)
api_router.include_router(forms.router)
api_router.include_router(calendar.router)
api_router.include_router(integrations.router)
api_router.include_router(integrations_realtime.router)
api_router.include_router(attachments.router)
api_router.include_router(search.router)
api_router.include_router(analytics.router)
api_router.include_router(my_analytics.router)
api_router.include_router(admin.router)
api_router.include_router(ws.router)
