import {
  AtSign,
  Calendar,
  CalendarClock,
  CheckCircle2,
  GitCommit,
  GitMerge,
  GitPullRequest,
  Hand,
  MessageCircle,
  Play,
  Share2,
  Shield,
  Sparkles,
  Trophy,
  UserMinus,
  UserPlus,
  Users,
  type LucideIcon,
} from 'lucide-react'

const ICONS: Record<string, LucideIcon> = {
  comment_mention: AtSign,
  chat_mention: AtSign,
  doc_mention: AtSign,
  comment_reply: MessageCircle,
  task_assigned: UserPlus,
  project_team_assigned: Users,
  task_shared: Share2,
  goal_shared: Trophy,
  goal_folder_shared: Trophy,
  goal_completed: CheckCircle2,
  goal_owner_assigned: UserPlus,
  goal_target_owner_assigned: UserPlus,
  workspace_invite: Hand,
  space_invite: Hand,
  project_invite: Hand,
  due_date_reminder: Calendar,
  task_overdue: CalendarClock,
  workspace_member_added: UserPlus,
  workspace_role_changed: Shield,
  workspace_member_removed: UserMinus,
  project_role_changed: Shield,
  team_member_added: Users,
  team_role_changed: Shield,
  team_member_removed: UserMinus,
  sprint_started: Play,
  sprint_completed: CheckCircle2,
  github_pr_opened: GitPullRequest,
  github_pr_merged: GitMerge,
  github_commit_pushed: GitCommit,
  user_onboarded: Sparkles,
}

export function notificationTypeIcon(type: string): LucideIcon {
  return ICONS[type] ?? MessageCircle
}
