"""profile status avatar

Revision ID: bee0840b1daf
Revises: 37e132f3551b
Create Date: 2026-06-10 21:49:08.752112+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'bee0840b1daf'
down_revision: Union[str, None] = '37e132f3551b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('avatar_color', sa.String(length=20), nullable=True))
    op.add_column('profiles', sa.Column('avatar_key', sa.String(length=500), nullable=True))
    op.add_column('profiles', sa.Column('status_text', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('profiles', 'status_text')
    op.drop_column('profiles', 'avatar_key')
    op.drop_column('profiles', 'avatar_color')
    # ### end Alembic commands ###
